import { notFound } from "next/navigation";
import { Container } from "@/components/Container";
import { BulletList, InfoSection } from "@/components/ContentBlocks";
import { RelatedLinks } from "@/components/RelatedLinks";
import { ScoreBadge } from "@/components/ScoreBadge";
import { SourceBlock } from "@/components/SourceBlock";
import { getBrief, briefs } from "@/data/briefs";
import { stocks } from "@/data/stocks";
import { themes } from "@/data/themes";
import { learnItems } from "@/data/learn";
import { metadata } from "@/lib/seo";
import { disclaimer, formatDate } from "@/lib/utils";
export function generateStaticParams() { return briefs.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const brief = getBrief(slug); return brief ? metadata(brief.title, `${brief.title}의 핵심 맥락, 관련 기업과 관찰 지표를 정리한 정보성 아카이브입니다.`, `/briefs/${brief.slug}`) : {}; }
export default async function BriefDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const brief = getBrief(slug); if (!brief) notFound(); const map = (source: { slug: string; name?: string; title?: string }[], values: string[]) => values.map((slug) => { const v = source.find((x) => x.slug === slug); return { slug, label: v?.name ?? v?.title ?? slug }; }); return <Container className="py-12"><div className="border-b border-[#20344c] pb-9"><p className="eyebrow">ARCHIVE BRIEF</p><div className="mt-3 flex items-start justify-between gap-5"><h1 className="max-w-3xl text-3xl font-semibold leading-tight sm:text-4xl">{brief.title}</h1><ScoreBadge score={brief.impactScore} /></div><p className="mt-4 text-sm text-slate-500">{formatDate(brief.date)} · 아카이브 예시</p><p className="mt-2 text-sm leading-6 text-slate-400">기업 이해를 위한 브리프 형식 예시이며, 실시간 뉴스나 최신 발표를 전달하지 않습니다.</p><ol className="mt-7 grid gap-3 md:grid-cols-3">{brief.summary.map((line, index) => <li className="rounded-lg border border-[#29435e] bg-[#0b1a2b] p-4 text-sm leading-6 text-slate-300" key={line}><span className="mr-2 font-mono text-cyan-300">0{index + 1}</span>{line}</li>)}</ol></div><div className="mt-8 grid gap-5 lg:grid-cols-2"><InfoSection title="무슨 일이 있었나"><p>{brief.whatHappened}</p></InfoSection><InfoSection title="왜 중요한가"><p>{brief.whyItMatters}</p></InfoSection><InfoSection title="단기 영향"><p>{brief.shortTermImpact}</p></InfoSection><InfoSection title="장기 영향"><p>{brief.longTermImpact}</p></InfoSection><InfoSection title="긍정 시나리오"><p>{brief.bullView}</p></InfoSection><InfoSection title="부정 시나리오"><p>{brief.bearView}</p></InfoSection><InfoSection title="다음에 확인할 지표"><BulletList items={brief.nextMetrics} /></InfoSection><RelatedLinks title="관련 기업" kind="stocks" items={map(stocks, brief.relatedStocks)} /><RelatedLinks title="관련 테마" kind="themes" items={map(themes, brief.relatedThemes)} /><RelatedLinks title="관련 개념" kind="learn" items={map(learnItems, brief.relatedLearn)} /></div><section className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/5 p-5 text-sm leading-6 text-amber-100"><p className="font-semibold">정보·학습 목적 안내</p><p className="mt-1">이 브리프는 원문 기사 전체 번역이 아니라, 기업 이해를 돕기 위한 요약·해설 형식의 콘텐츠입니다. {disclaimer}</p></section><section className="mt-5 panel rounded-xl p-5"><p className="eyebrow">SOURCES</p><h2 className="mt-2 font-semibold">출처 및 확인 자료</h2><div className="mt-3"><SourceBlock sources={brief.sources} /></div></section></Container>; }
