import Link from "next/link";
import { Container } from "@/components/Container";
import { SectionHeader } from "@/components/SectionHeader";
import { StockCard } from "@/components/StockCard";
import { ThemeCard } from "@/components/ThemeCard";
import { BriefCard } from "@/components/BriefCard";
import { stocks } from "@/data/stocks";
import { themes } from "@/data/themes";
import { briefs } from "@/data/briefs";
import { learnItems } from "@/data/learn";
import { metadata } from "@/lib/seo";
export const generateMetadata = () => metadata("성장주 아카이브", "AI, 반도체, 우주, 전력 인프라 등 미래 산업 기업을 쉽게 이해하는 성장주 아카이브", "/");
export default function Home() { return <><section className="gridline overflow-hidden border-b border-[#20344c]"><Container className="py-20 sm:py-28"><p className="eyebrow">FUTURE INDUSTRY ARCHIVE</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold leading-[1.16] tracking-tight sm:text-6xl">미래 산업 기업을 쉽게 이해하는 <span className="text-cyan-300">성장주 아카이브</span></h1><p className="mt-7 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">AI, 반도체, 우주, 전력 인프라 등 미래 산업 기업의 사업모델, 성장 동력, 핵심 지표, 리스크를 한국 투자자 관점에서 정리합니다.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="rounded-md bg-cyan-300 px-4 py-3 text-sm font-bold text-[#06101d]" href="/stocks">기업 설명서 둘러보기</Link><Link className="rounded-md border border-[#36516c] px-4 py-3 text-sm text-slate-200" href="/methodology">아카이브 방법론</Link></div></Container></section><Container className="space-y-20 py-16"><section><SectionHeader eyebrow="TENBAGGER WATCHLIST" title="주요 기업 설명서" description="가격 예측이 아닌 사업 구조와 관찰 포인트 중심의 기업 아카이브입니다." href="/stocks" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{stocks.slice(0, 6).map((stock) => <StockCard key={stock.slug} stock={stock} />)}</div></section><section><SectionHeader eyebrow="THEME MAP" title="산업의 연결고리" description="기술과 공급망을 테마별로 지도로 정리했습니다." href="/themes" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{themes.map((theme) => <ThemeCard key={theme.slug} theme={theme} />)}</div></section><section><SectionHeader eyebrow="ARCHIVE BRIEFS" title="최근 브리프" description="속보가 아닌, 기업 이해를 돕는 요약·해설 중심의 아카이브 노트입니다." href="/briefs" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{briefs.map((brief) => <BriefCard key={brief.slug} brief={brief} />)}</div></section><section><SectionHeader eyebrow="START HERE" title="초보자용 핵심 개념" href="/learn" /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{learnItems.slice(0, 5).map((item) => <Link className="panel rounded-xl p-4 hover:border-cyan-300/50" href={`/learn/${item.slug}`} key={item.slug}><p className="font-semibold">{item.title}</p><p className="mt-2 text-xs leading-5 text-slate-400">{item.shortDefinition}</p></Link>)}</div></section><section className="panel rounded-2xl p-7 sm:p-10"><p className="eyebrow">METHODOLOGY</p><h2 className="mt-3 text-2xl font-semibold">좋은 헤드라인보다, 반복해 확인할 수 있는 구조를 남깁니다.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-400">기업의 역할, 성장 동력, 리스크, 그리고 다음에 확인할 지표를 한곳에 연결합니다.</p><Link className="mt-6 inline-block text-sm text-cyan-300" href="/methodology">방법론 읽기 →</Link></section></Container></>; }
